version: "3.9"
services:
  nginx:
    depends_on:
      - fastify-backend
      - edgedb
      - certbot
    image: nginx-presio
    build: ./nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main-network
    environment:
      - NGINX_HOST=presio.app
      - NGINX_PORT=80

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email mathiasboulay@free.fr -d presio.app -d www.presio.app --agree-tos
      

  fastify-backend:
    depends_on:
      - edgedb
    image: fastify-backend
    build: ./fastify-backend
    networks:
      - main-network
    expose:
      - 8080
    environment:
      - GOOGLE_AUTH_ID=${GOOGLE_AUTH_ID}
      - GOOGLE_AUTH_SECRET=${GOOGLE_AUTH_SECRET}
      - GOOGLE_AUTH_RETURN_URI=${GOOGLE_AUTH_RETURN_URI}
      - CLOUDFLARE_R2_ACCESS_ID=${CLOUDFLARE_R2_ACCESS_ID}
      - CLOUDFLARE_R2_ACCESS_KEY=${CLOUDFLARE_R2_ACCESS_KEY}
      - CLOUDFLARE_R2_ACCOUNT_ID=${CLOUDFLARE_R2_ACCOUNT_ID}

  edgedb:
    image: edge-db
    build: ./edge-db
    volumes:
      - edgedb-data:/var/lib/edgedb/data
    ports:
      - 5656:5656
    expose:
      - 5656
    networks:
      - main-network
    environment:
      - EDGEDB_SERVER_SECURITY=insecure_dev_mode


volumes:
  edgedb-data:

networks:
  main-network:
