version: "3.9"
services:
  fastify-backend:
    depends_on:
      - edgedb
    image: fastify-backend
    build: ./fastify-backend
    networks:
      - main-network
    ports:
      - 3030:8080

  edgedb:
    image: edge-db
    build: ./edge-db
    environment:
      - EDGEDB_SERVER_SECURITY=insecure_dev_mode
    volumes:
      - edgedb-data:/var/lib/edgedb/data
    ports:
      - 5656:5656
    expose:
      - 5656
    networks:
      - main-network


volumes:
  edgedb-data:

networks:
  main-network:
